version: 2
updates:
- package-ecosystem: bundler
  directory: /
  schedule:
    interval: daily
    time: "22:00"
  reviewers:
    - andrcuns
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  reviewers:
    - andrcuns
