name: arm-images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Gemfile.lock

jobs:
  dependabot-version:
    name: Get Dependabot version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.dependabot-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch dependabot version
        id: dependabot-version
        run: |
          version=$(echo `awk '/dependabot-omnibus \([0-9.]+\)/ {print $2}' Gemfile.lock | sed 's/[()]//g'`)
          echo "version=$version" >> "$GITHUB_OUTPUT"

  build-push-core-image:
    name: Build Core
    runs-on: ubuntu-latest
    needs: dependabot-version
    steps:
      - name: Checkout dependabot repository
        uses: actions/checkout@v4
        with:
          repository: dependabot/dependabot-core
          ref: v${{ needs.dependabot-version.outputs.version }}
          submodules: recursive

      - name: Docker tags
        id: tags
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/dependabot-gitlab/dependabot-updater-core
          flavor: latest=true
          tags: |
            type=semver,pattern={{version}},value=${{ needs.dependabot-version.outputs.version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PUSH_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.tags.outputs.tags }}
          file: Dockerfile.updater-core

  build-push-updater-image:
    name: Build Ecosystems
    runs-on: ubuntu-latest
    needs:
      - dependabot-version
      - build-push-core-image
    strategy:
      fail-fast: false
      matrix:
        suite:
          - { name: bundler, ecosystem: bundler }
          - { name: cargo, ecosystem: cargo }
          - { name: composer, ecosystem: composer }
          - { name: docker, ecosystem: docker }
          - { name: elm, ecosystem: elm }
          - { name: git_submodules, ecosystem: gitsubmodule }
          - { name: github_actions, ecosystem: github-actions }
          - { name: go_modules, ecosystem: gomod }
          - { name: gradle, ecosystem: gradle }
          - { name: hex, ecosystem: mix }
          - { name: maven, ecosystem: maven }
          - { name: npm_and_yarn, ecosystem: npm }
          - { name: nuget, ecosystem: nuget }
          - { name: pub, ecosystem: pub }
          - { name: python, ecosystem: pip }
          - { name: terraform, ecosystem: terraform }
    steps:
      - name: Checkout dependabot repository
        uses: actions/checkout@v4
        with:
          repository: dependabot/dependabot-core
          ref: v${{ needs.dependabot-version.outputs.version }}
          submodules: recursive

      - name: Docker tags
        id: tags
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/dependabot-gitlab/dependabot-updater-${{ matrix.suite.ecosystem }}
          flavor: latest=true
          tags: |
            type=semver,pattern={{version}},value=${{ needs.dependabot-version.outputs.version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PUSH_TOKEN }}

      - name: Update base image
        run: |
          sed -i 's#dependabot/dependabot-updater-core#dependabot-gitlab/dependabot-updater-core#g' ${{ matrix.suite.name }}/Dockerfile

      - name: Build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: true
          # skip arm64 build for nuget due to issues with qemu: https://gitlab.com/qemu-project/qemu/-/issues/249
          platforms: ${{ matrix.suite.name == 'nuget' && 'linux/amd64' || 'linux/amd64,linux/arm64' }}
          cache-from: type=registry,ref=ghcr.io/dependabot-gitlab/dependabot-updater-${{ matrix.suite.ecosystem }}:latest
          cache-to: type=inline
          tags: ${{ steps.tags.outputs.tags }}
          file: ${{ matrix.suite.name }}/Dockerfile

  notify-release:
    name: Notify release for dependabot-gitlab
    runs-on: ubuntu-latest
    needs:
      - build-push-core-image
      - build-push-updater-image
    steps:
      - name: Notify
        run: |
          curl \
            -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Basic $(echo -n 'andrcuns:${{ secrets.DEPENDABOT_GITLAB_PASSWORD }}' | base64)" \
            -d '{"dependency_name": "dependabot-omnibus", "package_ecosystem": "bundler"}' \
            https://dependabot-gitlab.com/api/v2/notify_release
